name: a

on:
  workflow_dispatch:       

jobs:
  fetch_and_send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run fetch_data.py
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          URL: ${{ secrets.URL }}
          ONE: ${{ secrets.ONE }}
          THREE: ${{ secrets.THREE }}
        run: python fetch_data.py

      - name: Send data
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python tg.py

      - name: Send to Notion
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: python send_to_notion.py

      - name: Send to Discord
        run: python send_to_dis.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
  
      - name: Trigger Workflow B via GitHub API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/robot4black/Counts/actions/workflows/b.yaml/dispatches \
            -d '{"ref":"main"}'
